class_name StarterStreet
extends Node3D
## Starter Street (docs/STARTER_STREET.md). The scene file is generated by tools/build_starter_street.gd — edit the
## generator and rebuild rather than hand-editing the .tscn, or the next rebuild will undo it.
##
## At runtime this registers the street's spots with WorldState (shop = workplace, house = player home, bench and
## porch = sit spots) and pulls the player camera in to the closer over-the-shoulder framing of the reference.

## Closer, lower camera than the prototype default (4.5 m, 70°) — matches the gameplay reference framing.
@export var camera_distance := 3.4
@export var camera_height := 1.55
@export var camera_fov := 58.0

func _ready() -> void:
	_register_spots()
	var player := get_node_or_null("Player")
	if player:
		var spawn := get_node_or_null("NPCSpawns/PlayerSpawn") as Node3D
		if spawn:
			player.global_transform = spawn.global_transform
		frame_camera(player)

func frame_camera(player: Node) -> void:
	var rig := player.get_node_or_null("CameraRig") as Node3D
	var arm := player.get_node_or_null("CameraRig/SpringArm3D") as SpringArm3D
	var cam := player.get_node_or_null("CameraRig/SpringArm3D/Camera3D") as Camera3D
	if rig:
		rig.position.y = camera_height
	if arm:
		arm.spring_length = camera_distance
	if cam:
		cam.fov = camera_fov

func _register_spots() -> void:
	var world := get_node_or_null("/root/WorldState")
	if world == null:
		return
	for marker in get_node("NPCSpawns").get_children():
		if marker is Marker3D:
			world.register_location("street_" + String(marker.name).to_snake_case(), marker)
